### ISSUE TITLE
Project artifacts

### ISSUE THREAD

**Issue by jreznot** [cuba-platform/cuba-cli#6]
- [x] Entity, register in persistence.xml, write to messages.properties EntityClass = Entity Class
- [x] Enumeration
- [x] Screen, register in screens.xml, + messages.properties
- [x] Service - register in web-spring.xml
- [x] EntityListener - without parsing project, ask for class and types of listener
- [x] Bean - with `@Component` annotation in standard place of web / core
- [x] Generate app-component.xml
- [x] Theme extension (build.gradle, sample files, may be postponed)
